const ApiConstant = {
  Login: 'Login',
  Register: 'Register',
  Password: 'Password',
  VerifyOTP: 'VerifyOTP',
  ChangePassword: 'ChangePassword',
  ChangePasswordProfile: 'ChangePasswordProfile',
  SideMenu: 'SideMenu',
  Review: 'Review',
  UpcomingEvents: 'UpcomingEvents',
  Profile: 'Profile',
  EditProfile: 'EditProfile',
  InRoute: 'InRoute',
  Chat: 'Chat',
  PastEvents: 'PastEvents',
  RequestForm: 'RequestForm',
  ModelList: 'ModelList',
  MapSearchScreen: 'MapSearchScreen',
  PreferredScreen: 'PreferredScreen',
  MyTripScreen: 'MyTripScreen',
  Invite: 'Invite',
  CouponScreen: 'CouponScreen',
  AccountDetailScreen: 'AccountDetailScreen',
  Emergency: 'Emergency',
  ProfileScreen: 'ProfileScreen',
  WalletScreen: 'WalletScreen',
  About: 'About',
  Support: 'Support',

  URL: 'http://4ezone-api.ondemandcreations.com/',
  register: 'doctor/register',
  addGymdoc: 'gym/adddoc',
  updateGymdoc: 'gym/updatedoc',
  getAllSpecialist:'specialist/getAllSpecialist',
  doctorLogin:"doctor/login",
  getGymTrainers: 'gym/getTrainer/',
  deleteGymTrainer: 'gym/deleteGymTrainer',
  getGymSessions: 'gym/getSession/',
  getTrainerSessions: 'trainer/getSession/',
  addGymTrainer: 'gym/addtrainer',
  updateGymSession: 'gym/updatesession',
  addGymSession: 'gym/addsession',
  addTrainerSessions: 'trainer/addsession',
  updateTrainerSession: 'trainer/updatesession',
  gymtrainerLogin: 'gymtrainer/login',
  addTrainerdoc: 'trainer/adddoc',
  trainerRegister: 'trainer/register',
  forgotPassword: 'doctor/forgotpassword',
  verfiyMobile: 'user/login',
  resendotp: 'doctor/resendotp',
  loginMobile: 'user/password',
  updateprofile: 'doctor/updateprofile',
  updateTrainerprofile: 'trainer/updateprofile',
  changepassword: 'doctor/changepassword',
  resetpassword: 'doctor/resetpassword',
  profileimage: 'doctor/profileimage',
  profileTrainerimage: 'trainer/profileimage',
  onlineOfflineDoctor: 'doctor/doctorstatus',
  doctorCurrentOrders: 'doctor/orders',
  orderdetail: 'user/orderdetail/',
  doctorpastBooking:'doctor/history',
  doctorupcomingBooking:'doctor/deliveries',
  customerAcceptorder :'doctor/acceptorder',
  customerRejectorder :'doctor/rejectorder',
  startVideocalling:'doctor/startVideocalling',
  endVideocalling:'doctor/endVideocalling',

  doctorNearby :'doctor/getAllReferalDoctorNearby',
  chemistNearby:'doctor/getAllChemistNearby',
  labNearby:'doctor/getAllLabAssistantNearby',
  hospitalNearby:'doctor/getAllHospitalNearby',
  getChemistById:'doctor/getChemistById/',
  getLabById:'doctor/getLabAssistantById/',
  getHospitalById:'doctor/getHospitalById/',
  getDoctorById:'doctor/getReferalDoctorById/',

  assignOrdertoChemist:'doctor/assignOrdertoChemist',
  assignOrdertoLab:'doctor/assignOrdertoLabAssistant',
  assignOrdertoHospital:'doctor/assignOrdertoHospital',
  assignOrdertoDoctor :'doctor/assignOrdertoReferalDoctor',

  completeBooking:'doctor/completeBooking',

  gymAssignTrainer: 'booking/gymAssignTrainer',
  feedbackByDoctorToCustomer: 'driver/feedbackbydriver',
  getUpcomingDisputeGym: 'gym/getUpcomingDisputeGym',
  getUpcomingDisputeTrainer: 'trainer/getUpcomingDispute',
  addDisputeReplyGym: 'gym/addDisputeReplyGym',
  addDisputeReplyTrainer: 'trainer/addDisputeReplyTrainer',
  addDisputeReply: 'trainer/addDisputeReply',

  getDisputeById: 'gym/getDisputeById',
  
  gymRejectBooking: 'booking/gymRejectBooking',
  trainerRejectBooking: 'booking/trainerRejectBooking',
  getBookingDetailById: 'booking/getBookingDetailById/',
  getDoctorDayEarning:'stats/doctor/today/',
  getDoctorWeekEarning:'stats/doctor/week/',
 
  doctorAddaccount:'doctor/addaccount',
  gymChatHistory:'gym/gymChatHistory',
  trainerChatHistory:'trainer/trainerChatHistory',
  helpandsupport:'admin/helpandsupport',


  userPOS: 'payment/addpos',
  paymentMethodList: 'payment/poslist',
  deletePOS: 'payment/deletepos',
  estimatedCost: 'trip/estimatedcost',

  addMoney: 'payment/addmoney',
  emergencyContactList: 'user/getcontact',
  addEmergencyContact: 'user/addcontact',
  deleteEmergencyContact: 'user/removecontact',

  addTripURL: 'trip/addtrip',
  cancelTripURL: 'trip/customercancel',
  getTripRequestURL: 'trip/user/tripdetails/',
  ratingTripURL: 'trip/feedbackcustomer',
  panicURL: 'user/panicsms',
  preferDriverURL: 'trip/user/addpreferdriver',
  validatePromoCodeURl: 'promo/validatepromocode',
  preferDriverListURL: 'trip/user/preferdriverslist',
  allTripsURL: 'trip/user/alltrips',
  allPromosURL: 'promo/visibleList',
  loginWithSocialURl: 'user/acknowledgeSocialRegistration',
  supportEmailURL: 'admin/sendsupportemail',
  termsandconditions   :'admin/termsandconditions',
  profile: 'user/profile',
  addEvent: 'event/addevent',
  eventManagerUpcoming: 'event/eventManagerUpcoming',
  eventManagerPast: 'event/eventManagerPast',
  eventDetail: 'event/eventdetail',
  checkChat: 'chat/checkChat',
  kHeaderValues: {
    'Content-Type': 'application/json',
  },
  kMethodPostKey: 'post',
  kMethodGetKey: 'get',
  apiTypePost: 'post',
  apiTypeGet: 'get',
  responseType: 'json',

  DRIVER_FINDING_TRIPS: 'FindingTrips',
  TRIP_ON_TRIP: 'OnTrip',
  TRIP_PICKUP_INROUTE: 'PickupInroute',
  TRIP_ARRIVED: 'PickupArrived',
  TRIP_DESTINATION_INROUTE: 'DestinationInroute',
  TRIP_FINDING: 'FindingDrivers',
  TRIP_COMPLETED: 'Completed',
  TRIP_SCHEDULED: 'Scheduled',
  TRIP_CANCELLED: 'Cancelled',
  TRIP_WAITING_DRIVER: 'WatingForDriver',
  DRIVER_OFFLINE: 'Offline',
  DRIVER_POOL_TRIPS: 'OnPoolTrip',
};

export const SUCCESS = 'success';
export const FAILURE = 'failure';

export default ApiConstant;
