export const DOCUMENT_ADD_REQUEST = 'DOCUMENT_ADD_REQUEST';
export const DOCUMENT_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST';
export const DOCUMENT_LIST_REQUEST = 'DOCUMENT_LIST_REQUEST';
export const DOCUMENT_ADD_SUCCESS = 'DOCUMENT_ADD_SUCCESS';
export const DOCUMENT_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENT_LIST_SUCCESS = 'DOCUMENT_LIST_SUCCESS';
export const DOCUMENT_FAILURE = 'DOCUMENT_FAILURE';
