export const PASSRESET_REQUESTED = 'PASSRESET_REQUESTED';
export const PASSCHANGE_REQUESTED = 'PASSCHANGE_REQUESTED';

export const PASSRESET_SUCCESS = 'PASSRESET_SUCCESS';
export const PASSRESET_FAIL = 'PASSRESET_FAIL';

export const FORGOT_REQUEST ="FORGOT_REQUEST";