export const ADD_BOOING_SUCCESS = 'ADD_BOOING_SUCCESS';
export const ADD_BOOING_REQUEST = 'ADD_BOOING_REQUEST';
export const ADD_BOOING_FAILURE = 'ADD_BOOING_FAILURE';

export const GET_PAST_BOOKING_SUCCESS = 'GET_PAST_BOOKING_SUCCESS';
export const GET_PAST_BOOKING_REQUEST = 'GET_PAST_BOOKING_REQUEST';
export const GET_PAST_BOOKING_FAILURE = 'GET_PAST_BOOKING_FAILURE';

export const GET_UPCOMING_BOOKING_SUCCESS = 'GET_UPCOMING_BOOKING_SUCCESS';
export const GET_UPCOMING_BOOKING_REQUEST = 'GET_UPCOMING_BOOKING_REQUEST';
export const GET_UPCOMING_BOOKING_FAILURE = 'GET_UPCOMING_BOOKING_FAILURE';

export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST'

  export const ASSIGN_BOOING_FAILURE = 'ASSIGN_BOOING_FAILURE'
  export const ASSIGN_BOOING_SUCCESS = 'ASSIGN_BOOING_SUCCESS'
  export const ASSIGN_BOOING_REQUEST = 'ASSIGN_BOOING_REQUEST'
