export const GETPROFILE_REQUEST = 'GETPROFILE_REQUEST';
export const GETPROFILE_SUCCESS = 'GETPROFILE_SUCCESS';
export const GETPROFILE_FAILURE = 'GETPROFILE_FAILURE';

export const ONLINE_OFFILNE_REQUEST = 'ONLINE_OFFILNE_REQUEST';
export const ONLINE_OFFILNE_SUCCESS = 'ONLINE_OFFILNE_SUCCESS';
export const ONLINE_OFFILNE_FAILURE = 'ONLINE_OFFILNE_FAILURE';
