export const PROFILEIM_UPLOADED = 'PROFILEIM_UPLOADED';
export const PROFILEIM_REQUESTED = 'PROFILEIM_REQUESTED';

export const PROFILE_UPLOADED = 'PROFILE_UPLOADED';
export const PROFILE_REQUESTED = 'PROFILE_REQUESTED';


export const EDITPROFILE_FAIL = 'EDITPROFILE_FAIL';