

export const GET_INPROCESS_DISPUTE_SUCCESS = 'GET_INPROCESS_DISPUTE_SUCCESS';
export const GET_INPROCESS_DISPUTE_REQUEST = 'GET_INPROCESS_DISPUTE_REQUEST';
export const GET_INPROCESS_DISPUTE_FAILURE = 'GET_INPROCESS_DISPUTE_FAILURE';

export const GET_COMPLETED_DISPUTE_FAILURE = 'GET_COMPLETED_DISPUTE_FAILURE';
export const GET_COMPLETED_DISPUTE_REQUEST = 'GET_COMPLETED_DISPUTE_REQUEST';
export const GET_COMPLETED_DISPUTE_SUCCESS = 'GET_COMPLETED_DISPUTE_SUCCESS';

export const GET_DISPUTE_REQUEST = 'GET_DISPUTE_REQUEST'

export const SEND_TO_DISPUTE_REQUEST = 'SEND_TO_DISPUTE_REQUEST';
export const SEND_TO_DISPUTE_SUCCESS = 'SEND_TO_DISPUTE_SUCCESS';
export const SEND_TO_DISPUTE_FAIL = 'SEND_TO_DISPUTE_FAIL';


export const RATING_REQUEST = 'RATING_REQUEST';
export const RATING_SUCCESS = 'RATING_SUCCESS';
export const RATING_FAIL = 'RATING_FAIL';
export const UPDATE_DIPUTE_REQUEST = "UPDATE_DIPUTE_REQUEST"