export const GET_TRAINER_REQUEST = 'GET_TRAINER_REQUEST';
export const GET_TRAINER_SUCCESS = 'GET_TRAINER_SUCCESS';
export const GET_TRAINER_FAILURE = 'GET_TRAINER_FAILURE';


export const ADD_TRAINER_REQUEST = 'ADD_TRAINER_REQUEST';
export const ADD_TRAINER_SUCCESS = 'ADD_TRAINER_SUCCESS';
export const ADD_TRAINER_FAILURE = 'ADD_TRAINER_FAILURE';


export const DELETE_TRAINER_REQUEST = 'DELETE_TRAINER_REQUEST';
export const DELETE_TRAINER_SUCCESS = 'DELETE_TRAINER_SUCCESS';
export const DELETE_TRAINER_FAILURE = 'DELETE_TRAINER_FAILURE';
