// Import Image
const Images={
    cover:require('_images/cover.png'),
    videocall2:require('_images/videocall2.png'),

    speciality:require('_images/speciality.png'),
    experience:require('_images/experience.png'),
    availability:require('_images/availability.png'),
    back :require('_images/back.png'),
    mailLight :require('_images/mail.png'),
    arrowright:require('_images/arrowright.png'),
    logo :require('_images/logo.png'),
    lock :require('_images/lock.png'),
    nameIcon:require('_images/userprofile2.png'),
    menuMore:require('_images/Menu-more.png'),
    address2:require('_images/address2.png'),
    upload:require('_images/upload.png'),
    downArrow:require('_images/down-arrow.png'),
    tick:require('_images/tick.png'),
    thankyou:require('_images/thankyou.png'),
    hamburger:require('_images/toggle-bar-black.png'),
    hamburgerwhite:require('_images/toggle-bar.png'),

    online:require('_images/online.png'),
    offline:require('_images/offline.png'),
    clock:require('_images/clock.png'),
    gail:require('_images/gail.png'),
    dummyuser:require('_images/dummyuser.png'),
    addtrainer:require('_images/addtrainer.png'),
    homeprofile:require('_images/homeprofile.png'),
    invitefriend:require('_images/invitefriend.png'),
    myappointments:require('_images/myappointments.png'),
    support:require('_images/support.png'),
    wallet:require('_images/wallet.png'),
    dispute:require('_images/Dispute.png'),
    earning:require('_images/earning.png'),
    manageservice:require('_images/manageservice.png'),
    calender:require('_images/calender.png'),
    address2:require('_images/address2.png'),
    address1:require('_images/Address.png'),
    delete:require('_images/delete.png'),
    add:require('_images/plus.png'),
    editProfile:require('_images/editProfile.png'),
    editcolor:require('_images/editcolor.png'),
    progilebg:require('_images/profilebg.png'),
    helpandsupport:require('_images/Help.png'),
    logout:require('_images/logout.png'),
    adduser:require('_images/adduser.png'),
    price:require('_images/price.png'),
    additional:require('_images/additional.png'),
    backwhite:require('_images/backwhite.png'),
    listtick:require('_images/listtick.png'),
    wallet2:require('_images/wallet2.png'),
    contact:require('_images/contact.png'),
    emailgreen:require('_images/emailgreen.png'),
    phonegreen:require('_images/phonegreen.png'),
    callblack:require('_images/callblack.png'),

    refer:require('_images/refer.png'),
    bank:require('_images/bank.png'),
    edit:require('_images/edit.png'),
    payment:require('_images/paymentbank.png'),
    selectnumber:require('_images/selectnumber.png'),
    next :require('_images/next.png'),
    noImage: require('_images/noImage.jpg'),
    notfound:require('_images/notfound.png'),
    notfound2:require('_images/notfound2.jpg'),
    addOption: require('_images/Add_option.png'),

}
module.exports=Images;