export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST';
export const GET_REQUESTS_FAILURE = 'GET_REQUESTS_FAILURE';

export const ADD_ACCEPT_REJECT_REQUEST = "ADD_ACCEPT_REJECT_REQUEST"
export const ADD_ACCEPT_REJECT_SUCCESS = "ADD_ACCEPT_REJECT_SUCCESS"
export const ADD_ACCEPT_REJECT_FAILURE = "ADD_ACCEPT_REJECT_FAILURE"