
export const GET_NERBY_CHEMIST_REQUEST = 'GET_NERBY_CHEMIST_REQUEST';
export const GET_NERBY_CHEMIST_SUCCESS = 'GET_NERBY_CHEMIST_SUCCESS';
export const GET_NERBY_CHEMIST_FAILURE = 'GET_NERBY_CHEMIST_FAILURE';
