export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAIL = 'LOGOUT_REQUEST_FAIL';

export const SAVE_FCM_TOKEN_REQUEST = 'SAVE_FCM_TOKEN_REQUEST';
export const SAVE_FCM_TOKEN_SUCCESS = 'SAVE_FCM_TOKEN_SUCCESS';