export const GET_DAY_EARNING_SUCCESS = 'GET_DAY_EARNING_SUCCESS';
export const GET_DAY_EARNING_REQUEST = 'GET_DAY_EARNING_REQUEST';
export const GET_DAY_EARNING_FAILURE = 'GET_DAY_EARNING_FAILURE';

export const GET_WEEK_EARNING_SUCCESS = 'GET_WEEK_EARNING_SUCCESS';
export const GET_WEEK_EARNING_REQUEST = 'GET_WEEK_EARNING_REQUEST';
export const GET_WEEK_EARNING_FAILURE = 'GET_WEEK_EARNING_FAILURE';
